export enum BcrRoleEnum {
    QS = 'QS',
    CM = 'CM',
    PM = 'PM',
    PD = 'PD',
    MNGM = 'MNGM'
}

export enum BcrReasonEnum {
    PM_VO_AI_EI_SI = 'PM_VO_AI_EI_SI',
    PM_THEFT_DAMAGE = 'PM_THEFT_DAMAGE',
    PM_MOCKUP_BUDGET = 'PM_MOCKUP_BUDGET',
    PM_INACCURATE_BUDGET = 'PM_INACCURATE_BUDGET',
    PM_OTHERS = 'PM_OTHERS',
    QS_OVERALL_REMEASUREMENT = 'QS_OVERALL_REMEASUREMENT',
    QS_MOCKUP_BUDGET = 'QS_MOCKUP_BUDGET',
    QS_BUDGET_ADJUSTMENT = 'QS_BUDGET_ADJUSTMENT',
    QS_VO_CHANGES = 'QS_VO_CHANGES',
    OTHERS_REASON = 'OTHERS_REASON'
}

export enum BcrRecommendationEnum {
    REMAIN_BUDGET = 'REMAIN_BUDGET',
    CHANGE_BUDGET = 'CHANGE_BUDGET',
    ACCEPT_CHANGE_QS = 'ACCEPT_CHANGE_QS',
    REJECT_CHANGE_QS = 'REJECT_CHANGE_QS',
    ACCEPT_CHANGE_SITE = 'ACCEPT_CHANGE_SITE',
    ACCEPT_CHANGE_PD = 'ACCEPT_CHANGE_PD'
}
